'use client';
import { useMemo, useState } from 'react';
import { Trophy, Dumbbell, Home, Route, User, Play, ChevronLeft } from 'lucide-react';
import { exercises, programs, roadmap, achievements } from '@/data/content';

type Screen = 'home' | 'exercises' | 'programs' | 'roadmap' | 'progress';

export default function App(){
  const [screen,setScreen]=useState<Screen>('home');
  const [selected,setSelected]=useState<string|null>(null);
  const [done,setDone]=useState<number[]>([0,1,2]);
  const exercise=useMemo(()=>exercises.find(e=>e.id===selected),[selected]);
  if(exercise) return <div className="phone"><button className="btn dark" onClick={()=>setSelected(null)}>חזרה</button><div className="bigFigure"/><h1 className="detailTitle">{exercise.name}</h1><span className="pill">{exercise.level}</span><div className="section card"><b>שרירים עובדים</b><p className="muted">{exercise.muscle}</p><p>{exercise.desc}</p></div><div className="section card"><b>שלבי ביצוע</b>{exercise.steps.map((s,i)=><p key={s}>{i+1}. {s}</p>)}</div><div className="section card"><b>טעויות נפוצות</b>{exercise.mistakes.map(m=><p key={m}>• {m}</p>)}</div><button className="btn" style={{width:'100%',marginTop:16}}>הוסף לאימון</button></div>;
  return <div className="phone"><Header/>{screen==='home'&&<HomeScreen setScreen={setScreen}/>} {screen==='exercises'&&<Exercises setSelected={setSelected}/>} {screen==='programs'&&<Programs/>} {screen==='roadmap'&&<Roadmap done={done} setDone={setDone}/>} {screen==='progress'&&<Progress/>}<Tabs screen={screen} setScreen={setScreen}/></div>
}
function Header(){return <div className="top"><div><div className="brand">OSHER CALISTHENICS</div><div className="tag">Own Your Strength</div></div><div className="avatar">OC</div></div>}
function HomeScreen({setScreen}:{setScreen:(s:Screen)=>void}){return <><div className="hero"><h1>ברוך הבא, אושר</h1><p className="muted">האימון הבא שלך מוכן. בנה כוח, שליטה והרגלים.</p><div className="stats"><div className="stat"><b>17</b><span>רצף ימים</span></div><div className="stat"><b>1,240</b><span>XP</span></div><div className="stat"><b>Lv. 8</b><span>Athlete</span></div></div></div><div className="section workout"><h3>אימון היום</h3><p>Upper Body Strength · 38 דקות</p><button className="btn dark"><Play size={16}/> התחל אימון</button></div><div className="section"><h2>פעולות מהירות</h2><div className="grid"><button className="card" onClick={()=>setScreen('exercises')}>ספריית תרגילים</button><button className="card" onClick={()=>setScreen('roadmap')}>Skill Roadmap</button><button className="card" onClick={()=>setScreen('programs')}>תוכניות</button><button className="card" onClick={()=>setScreen('progress')}>הישגים</button></div></div></>}
function Exercises({setSelected}:{setSelected:(id:string)=>void}){return <><div className="section"><h2>ספריית תרגילים</h2><input className="search" placeholder="חפש תרגיל..."/><div className="grid">{exercises.map(e=><button key={e.id} className="card exercise" onClick={()=>setSelected(e.id)}><div className="figure"/><div><b>{e.name}</b><p className="muted">{e.level} · {e.muscle}</p></div></button>)}</div></div></>}
function Programs(){return <div className="section"><h2>תוכניות אימון</h2><div className="list">{programs.map(p=><div className="row program" key={p.name}><div><b>{p.name}</b><p className="muted">{p.time} · {p.focus}</p><div className="bar"><span style={{width:p.progress+'%'}}/></div></div><ChevronLeft color="#b7ff2a"/></div>)}</div></div>}
function Roadmap({done,setDone}:{done:number[],setDone:(v:number[])=>void}){return <div className="section"><h2>Skill Roadmap: Muscle Up</h2><div className="road">{roadmap.map((r,i)=><button key={r} className={'node card '+(done.includes(i)?'done':'')} onClick={()=>setDone(done.includes(i)?done.filter(x=>x!==i):[...done,i])}><span className="dot">{done.includes(i)?'✓':i+1}</span><div><b>{r}</b><p className="muted">לחץ לסימון התקדמות</p></div></button>)}</div></div>}
function Progress(){return <div className="section"><h2>התקדמות והישגים</h2><div className="hero"><h1>Level 8</h1><p>1,240 / 1,500 XP</p><div className="bar"><span style={{width:'72%'}}/></div></div><div className="list section">{achievements.map((a,i)=><div className="row" key={a}><div><b>{a}</b><p className="muted">+{(i+1)*50} XP</p></div><div className="check">✓</div></div>)}</div></div>}
function Tabs({screen,setScreen}:{screen:Screen,setScreen:(s:Screen)=>void}){const tabs:[Screen,string,any][]= [['home','בית',Home],['exercises','תרגילים',Dumbbell],['programs','תוכניות',Play],['roadmap','Roadmap',Route],['progress','הישגים',Trophy]];return <div className="tabs">{tabs.map(([id,label,Icon])=><button key={id} className={'tab '+(screen===id?'active':'')} onClick={()=>setScreen(id)}><Icon size={18}/><br/>{label}</button>)}</div>}
